/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MitigationRouteImport } from './routes/mitigation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecurityAttackTypesRouteImport } from './routes/security.attack-types'
import { Route as SecurityEventsIdRouteImport } from './routes/security.events.$id'

const MitigationRoute = MitigationRouteImport.update({
  id: '/mitigation',
  path: '/mitigation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityAttackTypesRoute = SecurityAttackTypesRouteImport.update({
  id: '/security/attack-types',
  path: '/security/attack-types',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityEventsIdRoute = SecurityEventsIdRouteImport.update({
  id: '/security/events/$id',
  path: '/security/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mitigation': typeof MitigationRoute
  '/security/attack-types': typeof SecurityAttackTypesRoute
  '/security/events/$id': typeof SecurityEventsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mitigation': typeof MitigationRoute
  '/security/attack-types': typeof SecurityAttackTypesRoute
  '/security/events/$id': typeof SecurityEventsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/mitigation': typeof MitigationRoute
  '/security/attack-types': typeof SecurityAttackTypesRoute
  '/security/events/$id': typeof SecurityEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/mitigation'
    | '/security/attack-types'
    | '/security/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/mitigation'
    | '/security/attack-types'
    | '/security/events/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/mitigation'
    | '/security/attack-types'
    | '/security/events/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MitigationRoute: typeof MitigationRoute
  SecurityAttackTypesRoute: typeof SecurityAttackTypesRoute
  SecurityEventsIdRoute: typeof SecurityEventsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mitigation': {
      id: '/mitigation'
      path: '/mitigation'
      fullPath: '/mitigation'
      preLoaderRoute: typeof MitigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/attack-types': {
      id: '/security/attack-types'
      path: '/security/attack-types'
      fullPath: '/security/attack-types'
      preLoaderRoute: typeof SecurityAttackTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/events/$id': {
      id: '/security/events/$id'
      path: '/security/events/$id'
      fullPath: '/security/events/$id'
      preLoaderRoute: typeof SecurityEventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MitigationRoute: MitigationRoute,
  SecurityAttackTypesRoute: SecurityAttackTypesRoute,
  SecurityEventsIdRoute: SecurityEventsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
